### ISSUE TITLE
Issue abot preprocessing.py 

### ISSUE THREAD

**Issue by Chuttyboy** [irdanish11/AnomalyEventDetection#3]
Hello @irdanish11 @junaid340 

I got this error while preprocessing Avenue Dataset 

![Screenshot from 2021-08-21 18-54-03](https://user-images.githubusercontent.com/79959547/130388138-b217347a-3add-402d-9b34-2d110c0f052d.png)

Thank you

**Comment by irdanish11** [comment]
@junaid340 can you please have a look at the issue?
