### ISSUE TITLE
doubt

### ISSUE THREAD

**Issue by t-v-k-git** [irdanish11/AnomalyEventDetection#4]
Hi, 
Thank you for your work, but can you help me in resolving doubt about how do we get the threshold value????

        if data_model=='UCSD':
            threshold=0.00026
        elif data_model=='Avenue':
            threshold=0.00040

once again thank you for great work and everything with comments I really appreciate your efforts

**Comment by irdanish11** [comment]
@t-v-k-git you are welcome.
The threshold values were set after testing the respective models on the respective test sets. So after these values, we were able to spot the anomalies.

**Comment by irdanish11** [comment]
Let me know if that helps you and I'll close this issue.
